name: Build and push

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get latest image version
        id: get_latest_version
        run: |
          IMAGE_NAME="medhedimaaroufi/callcenterai-svm"
          # Get tags from Docker Hub API
          LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/${IMAGE_NAME}/tags?page_size=100" \
            | jq -r '.results[].name' \
            | grep -E '^v1\.0\.[0-9]+$' \
            | sort -V \
            | tail -n1)
          echo "Latest tag: $LATEST_TAG"
          
          if [[ -z "$LATEST_TAG" ]]; then
            NEXT_TAG="v1.0.1"
          else
            # Extract the number after v1.0.
            NUMBER=$(echo $LATEST_TAG | sed 's/v1\.0\.//')
            NUMBER=$((NUMBER + 1))
            NEXT_TAG="v1.0.$NUMBER"
          fi
          echo "NEXT_TAG=$NEXT_TAG" >> $GITHUB_ENV
          echo "New image tag will be: $NEXT_TAG"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: medhedimaaroufi/callcenterai-svm:${{ env.NEXT_TAG }}

      - name: Run Trivy security scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'medhedimaaroufi/callcenterai-svm:${{ env.NEXT_TAG }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'
