name: Lint

on: [workflow_call]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort

      - name: Upload code
        uses: actions/upload-artifact@v4
        with:
          name: source-code
          path: .
          retention-days: 1

  black:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: source-code

      - name: Run black
        run: black --check .

  flake8:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: source-code

      - name: Run flake8
        run: flake8 . --max-line-length=88 --extend-ignore=E203

  isort:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: source-code

      - name: Run isort
        run: isort --check-only --diff .