name: Stage CI Pipeline

on:
  push:
    branches: [main]


jobs:
  Lint:
    uses: ./.github/workflows/lint.yaml

  Test:
    uses: ./.github/workflows/test.yaml

  Build_and_Push:
    needs: [Lint, Test]
    environment: CallCenter-AI
    uses: ./.github/workflows/build_and_push.yaml
  
  Test_Secrets:
    environment: CallCenter-AI
    uses: ./.github/workflows/test_secrets.yaml