name: Stage CI Pipeline

on:
  push:
    branches: [main]


jobs:
  Lint:
    uses: ./.github/workflows/lint.yaml

  Test:
    uses: ./.github/workflows/test.yaml

  Build_and_Push:
    depends-on: [Lint, Test]
    uses: ./.github/workflows/build_and_push.yaml