name: Stage CI Pipeline

on:
  push:
    branches: [main]


jobs:
  Lint:
    uses: ./.github/workflows/lint.yaml

  Test:
    uses: ./.github/workflows/test.yaml

  Build_and_Push:
    needs: [Lint, Test]
    uses: ./.github/workflows/build_and_push.yaml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}