name: Echo secrets

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  test_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Docker username secret
        run: echo "The secret value is ${{ secrets.DOCKER_USERNAME }}"
      - name: Echo Docker password secret
        run: echo "The secret value is ${{ secrets.DOCKER_PASSWORD }}"
